name: build
on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
      - "NOTICE"
      - ".gitignore"
      - "libraries.properties"
      - "build.sh"
    tags:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.platform.host }}
    strategy:
      matrix:
        platform:
          - name: linux-x86_64
            arch_image: x86_64
            gcc_suffix: manylinux
            host: ubuntu-latest
          - name: linux-arm64
            arch_image: arm64
            gcc_suffix: manylinux
            host: arm64-server
          - name: muslinux-x86_64
            arch_image: x86_64
            gcc_suffix: muslinux
            host: ubuntu-latest
          - name: macos-arm64
            host: macos-15
          - name: windows-x86_64
            host: windows-2022
    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Set up QEMU
        if: matrix.platform.name == 'linux-arm64'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Setup MSYS2
        if: matrix.platform.name == 'windows-x86_64'
        uses: msys2/setup-msys2@v2

      - name: Detect Native CMake Path (Windows)
        id: detect_cmake
        if: matrix.platform.name == 'windows-x86_64'
        shell: powershell
        run: |
          $cmake = (Get-Command cmake).Source
          echo "cmake_path=$cmake" >> $env:GITHUB_ENV

      - name: Install dependencies (Windows)
        if: matrix.platform.name == 'windows-x86_64'
        shell: msys2 {0}
        run: pacman -S --noconfirm base-devel git nasm ninja

      - name: Set up Python (Windows)
        uses: actions/setup-python@v6
        if: matrix.platform.name == 'windows-x86_64' || matrix.platform.name == 'macos-arm64'
        id: python
        with:
          python-version: "3.14"

      - name: Build OpenH264 Library with Docker
        if: matrix.platform.name == 'linux-x86_64' || matrix.platform.name == 'linux-arm64' || matrix.platform.name == 'muslinux-x86_64'
        run: |
          docker run --rm -v $(pwd):/app -w /app --env GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
              ghcr.io/pytgcalls/ntgcalls/${{ matrix.platform.gcc_suffix }}-${{ matrix.platform.arch_image }}:latest bash build.sh

      - name: Build OpenH264 (Windows)
        if: matrix.platform.name == 'windows-x86_64'
        shell: msys2 {0}
        run: |
          export PATH="$(dirname "$(cygpath -u "$cmake_path")"):$PATH"
          export PATH="$(dirname "$(cygpath -u "${{ steps.python.outputs.python-path }}")"):$PATH"
          bash build.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build OpenH264 (macOS)
        if: matrix.platform.name == 'macos-arm64'
        run: bash build.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare for artifact (Linux, macOS and Android)
        if: matrix.platform.name != 'windows-x86_64'
        run: |
          tar -czvf openh264.${{ matrix.platform.name }}.tar.gz artifacts

      - name: Prepare for artifact (Windows)
        if: matrix.platform.name == 'windows-x86_64'
        run: |
          Compress-Archive -Path artifacts -DestinationPath openh264.${{ matrix.platform.name }}.zip

      - name: Upload artifact (Linux, macOS and Android)
        uses: actions/upload-artifact@v6
        if: matrix.platform.name != 'windows-x86_64'
        with:
          name: openh264.${{ matrix.platform.name }}.tar.gz
          path: openh264.${{ matrix.platform.name }}.tar.gz

      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v6
        if: matrix.platform.name == 'windows-x86_64'
        with:
          name: openh264.${{ matrix.platform.name }}.zip
          path: openh264.${{ matrix.platform.name }}.zip

  create-release:
    name: Create Release
    if: contains(github.ref, 'tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/download
        with:
          platform: windows-x86_64
      - uses: ./.github/actions/download
        with:
          platform: linux-x86_64
      - uses: ./.github/actions/download
        with:
          platform: linux-arm64
      - uses: ./.github/actions/download
        with:
          platform: muslinux-x86_64
      - uses: ./.github/actions/download
        with:
          platform: macos-arm64
      - name: Env to output
        run: |
          echo "package_paths<<EOF" >> $GITHUB_OUTPUT
          cat package_paths.env >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        id: env
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.env.outputs.package_paths }}